language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl
  - sudo apt-get update
  - sudo apt-get install cmake libvtk5-qt4-dev libboost-dev libflann-dev libeigen3-dev openni-dev
script: 
  - git clone https://github.com/PointCloudLibrary/pcl.git
  - cd pcl
  - mkdir build
  - cd build
  - cmake ..
  - make  
branches:
  only:
    - master
notifications:
  recipients:
    - julius@kammerl.com
  email:
    on_success: change
    on_failure: always
