language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo add-apt-repository ppa:nmi/vim-snapshots  -y
  - sudo apt-get update -d
  - sudo apt-get install cmake libvtk5-qt4-dev libflann-dev libeigen3-dev openni-dev libqhull-dev boost1.53 libusb-1.0-0-dev doxygen python-sphinx -qq
script: 
  - mkdir build && cd build
  - cmake -DPCL_ONLY_CORE_POINT_TYPES=ON .. && make -j4 && sudo make install && make test && make Tutorials && make doc
branches:
  only:
    - master
notifications:
  recipients:
    - julius@kammerl.com
  email:
    on_success: change
    on_failure: always
