language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install cmake
script: 
  - git clone https://github.com/PointCloudLibrary/pcl.git
  - cd pcl
  - mkdir build
  - cd build
  - cmake ..
  - make  
branches:
  only:
    - master
notifications:
  recipients:
    - julius@kammerl.com
  email:
    on_success: change
    on_failure: always
