language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update -dd
  - sudo apt-get install cmake libvtk5-qt4-dev libboost-dev libflann-dev libeigen3-dev openni-dev libqhull-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev libboost-date-time-dev libboost-iostreams-dev libusb-1.0-0-dev doxygen python-sphinx -qq
script: 
  - git clone https://github.com/PointCloudLibrary/pcl.git
  - cd pcl && mkdir build && cd build
  - cmake .. && make && make install && make test && make Tutorials && make doc
branches:
  only:
    - master
notifications:
  recipients:
    - julius@kammerl.com
  email:
    on_success: change
    on_failure: always
